g++ `root-config --cflags --glibs` -lGenVector DataYield1.C ConstrainedFit.cc -o fit1 && ./fit1
g++ `root-config --cflags --glibs` -lGenVector DataYield2.C ConstrainedFit.cc -o fit2 && ./fit2
g++ `root-config --cflags --glibs` -lGenVector DataYield3.C ConstrainedFit.cc -o fit3 && ./fit3
g++ `root-config --cflags --glibs` -lGenVector DataYield4.C ConstrainedFit.cc -o fit4 && ./fit4
g++ `root-config --cflags --glibs` -lGenVector DataYield5.C ConstrainedFit.cc -o fit5 && ./fit5
g++ `root-config --cflags --glibs` -lGenVector DataYield6.C ConstrainedFit.cc -o fit6 && ./fit6
g++ `root-config --cflags --glibs` -lGenVector DataYield7.C ConstrainedFit.cc -o fit7 && ./fit7
g++ `root-config --cflags --glibs` -lGenVector DataYield8.C ConstrainedFit.cc -o fit8 && ./fit8
g++ `root-config --cflags --glibs` -lGenVector DataYield9.C ConstrainedFit.cc -o fit9 && ./fit9
g++ `root-config --cflags --glibs` -lGenVector DataYield10.C ConstrainedFit.cc -o fit10 && ./fit10
g++ `root-config --cflags --glibs` -lGenVector DataYield11.C ConstrainedFit.cc -o fit11 && ./fit11
g++ `root-config --cflags --glibs` -lGenVector DataYield12.C ConstrainedFit.cc -o fit12 && ./fit12
g++ `root-config --cflags --glibs` -lGenVector DataYield13.C ConstrainedFit.cc -o fit13 && ./fit13
g++ `root-config --cflags --glibs` -lGenVector DataYield14.C ConstrainedFit.cc -o fit14 && ./fit14
g++ `root-config --cflags --glibs` -lGenVector DataYield15.C ConstrainedFit.cc -o fit15 && ./fit15
g++ `root-config --cflags --glibs` -lGenVector DataYield16.C ConstrainedFit.cc -o fit16 && ./fit16
g++ `root-config --cflags --glibs` -lGenVector DataYield17.C ConstrainedFit.cc -o fit17 && ./fit17
g++ `root-config --cflags --glibs` -lGenVector DataYield18.C ConstrainedFit.cc -o fit18 && ./fit18
g++ `root-config --cflags --glibs` -lGenVector DataYield19.C ConstrainedFit.cc -o fit19 && ./fit19
g++ `root-config --cflags --glibs` -lGenVector DataYield20.C ConstrainedFit.cc -o fit20 && ./fit20
